apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deploy
  labels: 
    type: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: httpd-pod
      labels:
        type: appserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080

...                
    
