---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjen-deploment
  labels:
    type: ci-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      type: ci-cd
  template:
    metadata:
      name: jenkins-pod
      labels:
        type: ci-cd
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 8081

...                

