---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment
  labels:
    author: abhi
    type: reverse-proxy
spec:
  replicas: 2
  selector: 
    matchLabels:
      type: reverse-proxy
  template:
    metadata:
      name: nginx-pod
      labels:
        type: reverse-proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...                
