---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: abhi
    type: database
spec:
  containers: 
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: myabhi
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb

...            
