apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    type: db
spec:
  containers:
    - name: mydb
      image: mysql
      ports:
        - containerPort: 3306
          hostPort: 8081
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: abhi
