---
apiVersion: v1
kind: Pod
metadata: 
  name: jenkins-pod
  labels:
    type: ci-cd
spec:
  containers:
    - name: myjen
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 8081

...            
