---
apiVersion: v1
kind: Pod
metadata:
  name: tomee-pod
  labels: 
    type: webserver
spec:
  containers:
    - name: mytomee
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 8081

...            
