apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
  labels:
    author: abhi
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels: 
        author: abhi
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080

...                
    
